### ISSUE TITLE
Does this support both 5' and 3' kits?

### ISSUE THREAD

**Issue by billytcl** [nanoporetech/sockeye#1]
This looks really cool! Does this support both the 5' and 3' kits, or only the 3' one?

**Comment by jbeaulaurier** [comment]
Hello,
The pipeline currently only supports the 3' kit, but I'm working on adding 5' support and this should be coming very soon.
-John

**Comment by billytcl** [comment]
Thanks!! We do a lot of 5' sequencing and have our own homebrew tool that's
published, but it's great to have an official software package that can
take us all the way to gene expression counts.

**Comment by callumparr** [comment]
Oh wow, this is great. As we used 5'-GEX but I got stuck with the processing. 

@jbeaulaurier Would it be 5'-GEX or only the 5'-TCR?

**Comment by callumparr** [comment]
> Thanks!! We do a lot of 5' sequencing and have our own homebrew tool that's published

Oh may I ask what paper this is? Do you have link to repository. We did at 5'-GEX a while ago and trying to find a pipeline to process. we had the parallel short-read library as well.

**Comment by billytcl** [comment]
Here you go!
https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02554-1

I haven't looked into too much of the code in sockeye on how it works but
we developed a way to demultiplex barcodes that's resistant to indels (as
we've been doing this back in the hac days when error rates were much
higher). We do a first pass using a k-mer based decomposition to narrow
down candidates, and then do edit distance matching.

Feel free to reach out to us directly if you have any questions.

**Comment by callumparr** [comment]
> Here you go! https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02554-1 I haven't looked into too much of the code in sockeye on how it works but we developed a way to demultiplex barcodes that's resistant to indels (as we've been doing this back in the hac days when error rates were much higher). We do a first pass using a k-mer based decomposition to narrow down candidates, and then do edit distance matching. Feel free to reach out to us directly if you have any questions.
> […](#)

Thanks for the info. Thats good to know because we lost the original FAST5 so HAC is the best we god right now.

**Comment by jbeaulaurier** [comment]
Hey folks, just wanted to alert you to the fact that I've just pushed 5' GEX support into Sockeye. Please have a look at the docs to see how to supply the kit name & version in the input sample sheet. But once that is correctly supplied, everything else should be taken care of behind the scenes and you'll get the same demultiplexed output as with the 3' kit.

Let me know if you run into any difficulties.
-John

**Comment by billytcl** [comment]
Thank you! Would be great to try it out. Any roadmap for isoform calling?

**Comment by callumparr** [comment]
Oh supergoi!! I will give it a go.

**Comment by callumparr** [comment]
@jbeaulaurier Is it possible to replace the download of the full 10x barcode set with a whitelist I have from a parallel short-read set? Presumably, this would run quicker and be more accurate? 

May I simply place the 10x barcode list I have from the MiSeq run in this directory 
`BC_LONGLIST_DIR: /PATH/TO/10X/DOWNLOADS/` and comment out the section in Snakefile to stop it from downloading the 10x longlist for the 5'-GEX kit? 

```
urls = {
    "3M-february-2018.txt.gz": "https://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/3M-february-2018.txt.gz",
    "737K-august-2016.txt": "https://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/737K-august-2016.txt",
}

ll_dir = config["BC_LONGLIST_DIR"]

if not os.path.exists(ll_dir):
    os.mkdir(ll_dir)

for fn in urls.keys():
    local_fn = os.path.join(ll_dir, fn)

    if not os.path.exists(local_fn):
        print(f"Downloading {fn} to {ll_dir}")
        with open(local_fn, "wb") as f:
            chunkSize = 1024
            r = requests.get(urls[fn], stream=True)
            with open(local_fn, "wb") as f:
                for chunk in r.iter_content(chunk_size=chunkSize):
                    if chunk:  # filter out keep-alive new chunks
                        f.write(chunk)
```
OR, even changing my file name to the name of the downloaded file. 

I have run from almost 4 years ago using r9.4.1 and LSK109 chemistry and guppy 'hac' basecalled but I no longer have the raw signal files to rebasecall and I think the accuracy is closer to the 93% so having a shortened list of possible barcodes would help?
