### ISSUE TITLE
Support of Cell x Transcript expression

### ISSUE THREAD

**Issue by albyrne0815** [nanoporetech/sockeye#14]
Hi,
Thanks for sockeye, I've used it and don't really have any issues but I was wondering if there is an interest in supporting transcript expression not just gene expression using the long read data after demuxing. Maybe being able to add your own gtf file after isoform calling using another pipeline would be good to incorporate.

**Comment by jbeaulaurier** [comment]
Hello,
Yes that is definitely something that I'm working on actively.
Best,
John
