### ISSUE TITLE
There is a bug in function `calc_ed_with_whitelist`

### ISSUE THREAD

**Issue by wangjianshou** [nanoporetech/sockeye#5]
```python
    for wl_bc in whitelist:
        d = ed.eval(bc_uncorr, wl_bc)
        if d < bc_match_ed:
            next_bc_match_ed = bc_match_ed
            bc_match_ed = d
            bc_match = wl_bc
    next_match_diff = next_bc_match_ed - bc_match_ed
   return bc_match, bc_match_ed, next_match_diff
```
The value of bc_match_ed is always correct, but the value of next_bc_match_ed is not necessarily correct, e.g when the edit distance between bc_uncorr and whitelist is [5, 3, 1, 4, 2, 3]. More generally, when the second smallest value is after the minimum value.

**Comment by jbeaulaurier** [comment]
Thanks very much for catching this. A fix has been pushed to `master` and is resolved in the v0.2.1 release.
