### ISSUE TITLE
snakemake DRMMA with slurm seems not to work.

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/sockeye#6]
I try modifying the flags passed by DRMMA from this:

```
snakemake --configfile config/config.yml --latency-wait 300 --drmaa ' -V -cwd -P <cluster_profile> -l m_mem_free={resources.mem}G -pe mt {threads} ' --default-resources mem=1 --jobs 1000 --use-conda --drmaa-log-dir ./drmaa_logs -pr all
```

I keep getting error:

```
WorkflowError:
DRMAA Error: code 14: Invalid native specification:   -V
```

in the end i just resorted to --cluser ' sbatch' for our slurm job scheduler rathre than relying on DRMMA. There appears to be an issue with what DRMMA supports for slurm

**Comment by jbeaulaurier** [comment]
Hello,
Sorry for the delayed reply here. I'm afraid I don't have experience with SLURM & DRMMA. But I would direct you to the Snakemake [documentation](https://snakemake.readthedocs.io/en/stable/executing/cluster.html) where they discuss SLURM/DRRMA:


>Are you using the SLURM job scheduler?
>
>In this case, it will be more robust to use the --cluster, --cluster-status, and --cluster-cancel arguments than using DRMAA. The reason is that the slurm-drmaa package is not maintained by the SLURM vendor SchedMD and less well supported. Effectively, you will run into timeouts in DRMAA calls sooner.

Best,
John
