### ISSUE TITLE
question: can sockeye identify biotin tagged base?

### ISSUE THREAD

**Issue by xxu1022** [nanoporetech/sockeye#7]
question: can sockeye identify biotin tagged base?

**Comment by jbeaulaurier** [comment]
Hello,
Unfortunately that's not within the scope of Sockeye's primary purpose, which is to demultiplex reads based on cell barcode and UMI sequences.

**Comment by xxu1022** [comment]
Hi @jbeaulaurier Thanks for your clarification. Appreciated!
